export const FETCHING_COMPANIES = "[COMPANY]FETCHING_COMPANIES";
export const FETCHING_COMPANIES_SUCCESS = "[COMPANY]FETCHING_COMPANIES_SUCCESS";
export const FETCHING_COMPANIES_FAILED = "[COMPANY]FETCHING_COMPANIES_FAILED";
export const FETCH_DATA_WHEN_FILTER_CHANGE = "[COMPANY]FETCH_DATA_WHEN_FILTER_CHANGE";
export const FETCH_DATA_WHEN_FILTER_CHANGE_SUCCESS = "[COMPANY]FETCH_DATA_WHEN_FILTER_CHANGE_SUCCESS";
export const FETCH_DATA_WHEN_FILTER_CHANGE_FAILED = "[COMPANY]FETCH_DATA_WHEN_FILTER_CHANGE_FAILED";